name: stacked_example
description: Stacked architecture example.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  # state management
  stacked: ^1.4.3
  # navigation
  auto_route:
  stacked_services:
  # inversion of control
  get_it:
  injectable:
  #
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  build_runner:
  auto_route_generator:
  injectable_generator:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true




























  #
  
  
